language: perl6
perl6:
  - latest
install:
  - rakudobrew build-panda
  - panda --notests installdeps .
script:
  - perl6 -MPanda::Builder -e 'Panda::Builder.build($*CWD)'
  - PERL6LIB=$PWD/blib/lib prove -e perl6 -vr t/
sudo: false
